<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add text here.' => 'Добавьте сюда текст.',
    'Be careful in Code field. Pay attention to field hint.' => 'Будьте внимательны при заполнении поля Код. Обратите внимание на подсказку.',
    'Code' => 'Код',
    'Create gallery' => 'Создать галерею',
    'Created at' => 'Время создания',
    'Created at {0, date, MMMM dd, YYYY HH:mm}' => 'Время создания: {0, date, dd MMMM YYYY, HH:mm}',
    'Description' => 'Описание',
    'Don\'t change this value, if you not sure for what it is for.' => 'Не меняйте значение этого поля, если не уверены в том для чего оно предназначено.',
    'Edit' => 'Изменить',
    'Galleries' => 'Галереи',
    'Gallery has been created' => 'Галерея была успешно создана',
    'Gallery has been deleted' => 'Галерея была удалена',
    'Gallery has been updated' => 'Галерея была изменена',
    'Information' => 'Информация',
    'Manage galleries' => 'Управление галереями',
    'Name' => 'Название',
    'Only latin characters, numbers and symbols (.-_) allowed. Spaces not allowed.' => 'Разрешены только латинские буквы, числа и символы (.-_). Пробелы запрещены.',
    'Save' => 'Сохранить',
    'Update gallery' => 'Изменить галерею',
    'Updated at' => 'Время изменения',
    '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, dd MMMM YYYY, HH:mm}',
];
